config/routes.rb
SphinksTest::Application.routes.draw do

  get "comments/create"

  devise_for :admins
  devise_for :users

  get "t_canvas/index"
  get "t_canvas/build"

  get "twit/index"
  get "twit/new"
  get "twit/create"

  root :to => "news_items#index"

  resources :search, :only => [] do
    get 'by_topic', :on => :member, :as => 'topic'
    get 'by_request', :on => :collection, :as => 'request'
  end

  resources :categories, :only => [] do
    resources :topics, :only => [] do
      get 'news', :on => :member, :to => 'search#by_topic'
    end
  end


  get "news_items/index"
  get "news_items/show/:id", :as => :show_news, :to => "news_items#show"
  get "news_items/load"
  get "news_items/load_last"
  get "news_items/change_rating"

  namespace :admins do
    resources :news_items
  end

  match '/admin' => 'admins/news_items#index'
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  field :user, :type => String
  field :message, :type => String
  field :news_item_id, :type => String

  #key :news_id, :required => true

  belongs_to :news_item

  validates :news_item_id, :user, :message, :presence => true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(params[:comment_attr])
    if comment.save!
      render :json => {:state => true, :comment => render_to_string(:partial =>'comments/show', :locals => {:comment => comment})}
    else
      render :json => {:state => false}
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
- if user_signed_in?
  %p Add comment
  =form_for :comment_attr, :html => {:remote => true} do |f|
    =f.text_area :message, {:rows => "5"}
    =f.submit 'Send', :onclick => "sendComment('#{comments_create_path}', '#{current_user.user_name}',
                                   $('#comment_attr_message').val(), '#{news_id.to_s}'); return false;"
- else
  You must registrates and/or authorize for posting comments

app/views/comments/_show.html.haml
.container
  =comment.user
  %span{:style => "float : right;"}= time_ago_in_words(comment.created_at)+" ago..."
  .clear
  %p= comment.message

app/views/comments/create.html.haml
%h1 Comments#create
%p Find me in app/views/comments/create.html.haml