config/routes.rb
SphinksTest::Application.routes.draw do

  get "comments/create"

  devise_for :admins
  devise_for :users

  get "t_canvas/index"
  get "t_canvas/build"

  get "twit/index"
  get "twit/new"
  get "twit/create"

  root :to => "news_items#index"

  resources :search, :only => [] do
    get 'by_topic', :on => :member, :as => 'topic'
    get 'by_request', :on => :collection, :as => 'request'
  end

  resources :categories, :only => [] do
    resources :topics, :only => [] do
      get 'news', :on => :member, :to => 'search#by_topic'
    end
  end


  get "news_items/index"
  get "news_items/show/:id", :as => :show_news, :to => "news_items#show"
  get "news_items/load"
  get "news_items/load_last"
  get "news_items/change_rating"

  namespace :admins do
    resources :news_items
  end

  match '/admin' => 'admins/news_items#index'
end

app/models/news_item.rb
class NewsItem
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Sphinx

  field :title, :type => String
  field :body,  :type => String

  belongs_to :topic
  has_many :comments, :dependent => :destroy
  has_many :ratings, :dependent => :destroy

  validates :title, :body, :presence => true

  search_index(:fields => [:title, :body],:attributes => [])
end

app/controllers/admins/news_items_controller.rb
class Admins::NewsItemsController < Admins::AdminsController

  def new
    @news_item = NewsItem.new
  end

  def create
    @news_item = NewsItem.new(params[:news_item])
    if @news_item.save
      redirect_to admins_news_items_path, :notice => "News successfully created"
    else
      render :new
    end
  end

  def edit
    @news_item = NewsItem.where(:_id => params[:id]).first
  end

  def index
    @news_items = NewsItem.all.paginate(:page => params[:page], :per_page => 15)
  end

  def show
    @news_item = NewsItem.where(:_id => params[:id]).first
  end

  def update
    @news_item = NewsItem.where(:_id => params[:id]).first
    @news_item.update_attributes(params[:news_item])
    redirect_to admins_news_items_path, :notice => "Object updated"
  end

  def destroy
    NewsItem.where(:id => params[:id]).destroy
    redirect_to admins_news_items_path, :notice => "Object deleted"
  end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  before_filter :init, :only => [:index]
  before_filter :authenticate_user!, :only => [:change_rating]

  #def new
  #  @news_item = NewsItem.new
  #end
  #
  #def create
  #  @news_item = NewsItem.new(params[:news_item_attr])
  #  if @news_item.save
  #    redirect_to news_items_index_path, :notice => "News successfully created"
  #  else
  #    render :new
  #  end
  #end

  def index
  end

  def show
    @news_item = NewsItem.includes(:comments).where(:_id => params[:id]).first
    gem = Rating.where({:user_id => current_user.id.to_s, :news_id => @news_item.id}).first if (user_signed_in?)
    @gem_num = gem ? gem.gems : 1
  end

  def load_last
    Parse.parse_last()
    redirect_to :root
  end

  def load
    Parse.parse_all()
    redirect_to :root
  end

  def change_rating
    rating = Rating.new(params[:rating_attr])
    render :json => {:state => rating.save}
  end

  protected
  def init
    if @curr_topic.blank? || @curr_category.blank?
      @news = NewsItem.all.paginate(:page => params[:page], :per_page => 15)
    else
      redirect_to news_category_topic_path(:category_id => @curr_category, :id => @curr_topic)
    end
  end

end

app/views/news_items/index.html.haml
- @news.each do |news_item|
    %p= link_to news_item.title, show_news_path(news_item)

= will_paginate @news

app/views/news_items/new.html.haml
-#=form_for @news_item do |f|
-#  =f.select :topic,
-#
-#
-#  =f.label :title
-#  =f.text_field :title
-#
-#  =f.label :body
-#  =f.text_area :body

app/views/news_items/show.html.haml
.flow_button
  =link_to image_tag('images.jpeg'), news_category_topic_path(:category_id => @curr_category, :id => @curr_topic, :page => @curr_page)

%p.title= @news_item.title
%br/
%p= raw @news_item.body

- if user_signed_in?
  .container
    %p.left_text #{"Насколько интересная статья ?"}
    .container.star_container
      .substar_container= raw ruby_line(@news_item.id, current_user.id, @gem_num)
    .clear

%p Comments
#comments
  -@news_item.comments.each do |comment|
    =render :partial => 'comments/show', :locals => {:comment => comment}
=render :partial => 'comments/form', :locals => {:news_id => @news_item.id}