config/routes.rb
SphinksTest::Application.routes.draw do

  get "comments/create"

  devise_for :admins
  devise_for :users

  get "t_canvas/index"
  get "t_canvas/build"

  get "twit/index"
  get "twit/new"
  get "twit/create"

  root :to => "news_items#index"

  resources :search, :only => [] do
    get 'by_topic', :on => :member, :as => 'topic'
    get 'by_request', :on => :collection, :as => 'request'
  end

  resources :categories, :only => [] do
    resources :topics, :only => [] do
      get 'news', :on => :member, :to => 'search#by_topic'
    end
  end


  get "news_items/index"
  get "news_items/show/:id", :as => :show_news, :to => "news_items#show"
  get "news_items/load"
  get "news_items/load_last"
  get "news_items/change_rating"

  namespace :admins do
    resources :news_items
  end

  match '/admin' => 'admins/news_items#index'
end

app/models/news_item.rb
class NewsItem
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Sphinx

  field :title, :type => String
  field :body,  :type => String

  belongs_to :topic
  has_many :comments, :dependent => :destroy
  has_many :ratings, :dependent => :destroy

  validates :title, :body, :presence => true

  search_index(:fields => [:title, :body],:attributes => [])
end

app/controllers/admins/news_items_controller.rb
class Admins::NewsItemsController < Admins::AdminsController

  def new
    @news_item = NewsItem.new
  end

  def create
    @news_item = NewsItem.new(params[:news_item])
    if @news_item.save
      redirect_to admins_news_items_path, :notice => "News successfully created"
    else
      render :new
    end
  end

  def edit
    @news_item = NewsItem.where(:_id => params[:id]).first
  end

  def index
    @news_items = NewsItem.all.paginate(:page => params[:page], :per_page => 15)
  end

  def show
    @news_item = NewsItem.where(:_id => params[:id]).first
  end

  def update
    @news_item = NewsItem.where(:_id => params[:id]).first
    @news_item.update_attributes(params[:news_item])
    redirect_to admins_news_items_path, :notice => "Object updated"
  end

  def destroy
    NewsItem.where(:id => params[:id]).destroy
    redirect_to admins_news_items_path, :notice => "Object deleted"
  end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  before_filter :init, :only => [:index]
  before_filter :authenticate_user!, :only => [:change_rating]

  #def new
  #  @news_item = NewsItem.new
  #end
  #
  #def create
  #  @news_item = NewsItem.new(params[:news_item_attr])
  #  if @news_item.save
  #    redirect_to news_items_index_path, :notice => "News successfully created"
  #  else
  #    render :new
  #  end
  #end

  def index
  end

  def show
    @news_item = NewsItem.includes(:comments).where(:_id => params[:id]).first
    gem = Rating.where({:user_id => current_user.id.to_s, :news_id => @news_item.id}).first if (user_signed_in?)
    @gem_num = gem ? gem.gems : 1
  end

  def load_last
    Parse.parse_last()
    redirect_to :root
  end

  def load
    Parse.parse_all()
    redirect_to :root
  end

  def change_rating
    rating = Rating.new(params[:rating_attr])
    render :json => {:state => rating.save}
  end

  protected
  def init
    if @curr_topic.blank? || @curr_category.blank?
      @news = NewsItem.all.paginate(:page => params[:page], :per_page => 15)
    else
      redirect_to news_category_topic_path(:category_id => @curr_category, :id => @curr_topic)
    end
  end

end

app/views/admins/news_items/_form.html.haml
.group
  = f.label :topic_id, t("activerecord.attributes.news_item.topic_id", :default => "Topic"), :class => :label
  = f.select :topic_id, Topic.all.collect {|p| [ p.title, p.id ] }

.group
  = f.label :title, t("activerecord.attributes.news_item.title", :default => "Title"), :class => :label
  = f.text_field :title, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :body, t("activerecord.attributes.news_item.body", :default => "Body"), :class => :label
  = f.text_area :body, {:class => 'text_field', :style => "width : 100%"}
  %span.description Ex: a text block
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), admins_news_items_path, :class => "text_button_padding link_button"

app/views/admins/news_items/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/admins/news_items/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admins_news_items_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admins_news_item_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admins_news_item_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      NewsItem
    .inner
      = form_for @news_item, :url => admins_news_item_path(@news_item), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admins/news_items/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", admins_news_items_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admins_news_item_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      NewsItems
    .inner
      %table.table
        %tr
          %th.first Title
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @news_items.each do |news_item|
          %tr{:class => cycle("odd", "even")}
            %td{:width => "60%"}
              = link_to news_item.title, admins_news_item_path(news_item)
            %td{:width => "25%"}
              = news_item.created_at
            %td.last
              #{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admins_news_item_path(news_item)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", admins_news_item_path(news_item), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admins/news_items/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admins_news_items_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_admins_news_item_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      NewsItem
    .inner
      = form_for @news_item, :url => admins_news_items_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admins/news_items/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admins_news_items_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admins_news_item_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", admins_news_item_path
  .content
    .inner
      %p
        %b
          #{@news_item.topic.title} >> #{@news_item.title}
        = raw @news_item.body
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admins_news_item_path(@news_item), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "") + " " + t("web-app-theme.delete", :default => "Delete"), admins_news_item_path(@news_item), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')