config/routes.rb
SphinksTest::Application.routes.draw do

  get "comments/create"

  devise_for :admins
  devise_for :users

  get "t_canvas/index"
  get "t_canvas/build"

  get "twit/index"
  get "twit/new"
  get "twit/create"

  root :to => "news_items#index"

  resources :search, :only => [] do
    get 'by_topic', :on => :member, :as => 'topic'
    get 'by_request', :on => :collection, :as => 'request'
  end

  resources :categories, :only => [] do
    resources :topics, :only => [] do
      get 'news', :on => :member, :to => 'search#by_topic'
    end
  end


  get "news_items/index"
  get "news_items/show/:id", :as => :show_news, :to => "news_items#show"
  get "news_items/load"
  get "news_items/load_last"
  get "news_items/change_rating"

  namespace :admins do
    resources :news_items
  end

  match '/admin' => 'admins/news_items#index'
end

app/models/admin.rb
class Admin
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/category.rb
class Category
  include Mongoid::Document
  #include Mongoid::Timestamps::Created

  field :title, :type => String

  has_many :topics, :dependent => :destroy

  validates :title, :presence => true, :uniqueness => true
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  field :user, :type => String
  field :message, :type => String
  field :news_item_id, :type => String

  #key :news_id, :required => true

  belongs_to :news_item

  validates :news_item_id, :user, :message, :presence => true
end

app/models/news.rb
class News
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Sphinx

  field :title, :type => String
  field :body,  :type => String
  field :news_id, :type => String

  #key :topic_id, :title, :required => true

  belongs_to :topic
  has_many :comments

  validates :title, :body, :presence => true

  search_index(:fields => [:title, :body],:attributes => [])
end

app/models/news_item.rb
class NewsItem
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Sphinx

  field :title, :type => String
  field :body,  :type => String

  belongs_to :topic
  has_many :comments, :dependent => :destroy
  has_many :ratings, :dependent => :destroy

  validates :title, :body, :presence => true

  search_index(:fields => [:title, :body],:attributes => [])
end

app/models/rating.rb
class Rating
  include Mongoid::Document
  field :gems, :type => Integer, :default => 1
  field :user_id, :type => String
  field :news_id, :type => String

  validates :gems, :numericality => {:greater_than => 0, :less_than => 6}
  validates :user_id, :uniqueness => {:scope => :news_id}
  validates :news_id, :presence => true
end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Sphinx

  field :title, :type => String

  has_many :news_items, :dependent => :destroy
  belongs_to :category

  search_index(:fields => [:title], :attributes => [])

  validates :title, :presence => true, :uniqueness => {:scope => :category_id}
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  field :user_name, :type => String

  attr_accessible :user_name, :email, :password, :password_confirmation, :remember_me
  has_many :ratings, :dependent => :destroy

  validates :user_name, :presence => true, :uniqueness => true, :length => 3..12
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(params[:comment_attr])
    if comment.save!
      render :json => {:state => true, :comment => render_to_string(:partial =>'comments/show', :locals => {:comment => comment})}
    else
      render :json => {:state => false}
    end
  end
end

app/controllers/newses_controller.rb
class NewsesController < ApplicationController
  before_filter :init, :only => [:index]
  before_filter :authenticate_user!, :only => [:change_rating]

  def index
  end

  def show
    @news_item = News.includes(:comments).where(:_id => params[:id]).first
    @gem = Rating.where({:user_id => current_user.id.to_s, :news_id => @news_item.id}).first if (user_signed_in?)
    @gem_num = @gem ? @gem.gems : 1;
  end

  def load_last
    Parse.parse_last()
    redirect_to :root
  end

  def load
    Parse.parse_all()
    redirect_to :root
  end

  def change_rating
    rating = Rating.new(params[:rating_attr])
    render :json => {:state => rating.save}
  end

  protected
  def init
    @news = News.all.paginate(:page => params[:page], :per_page => 15)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def by_topic
    @news = NewsItem.where(:topic_id => params[:id]).paginate(:page => params[:page], :per_page => 15)
    render 'news_items/index'
  end

  def by_request
    @news = (params[:search] ? NewsItem.search(params[:search][:search]) : NewsItem.all).paginate(:page => params[:page], :per_page => 15)
    render 'news_items/index'
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
end

app/controllers/twit_controller.rb
class TwitController < ApplicationController
  def index
    @twits = Twitter.home_timeline({:count => 50})
  end

  def new
  end

  def create
    #Twitter.update(params[:twit])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def header_menu(items)
    content_tag(:ul, :id => "primary_menu") do
      raw(items.inject("") {|str, item| str+=content_tag(:li, :class => 'top_menu_item') { link_to item[0], item[1] }})
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/news_helper.rb
module NewsHelper
  def ruby_line(news_id, user_id,on_limit=1)
    ret = ""
    5.times do |index|
      ret+="<div id='star_#{index.to_s}' class='#{index < on_limit ? "check_ruby" : "uncheck_ruby"}' onclick=\"sendRating(this,'#{news_id}', '#{user_id}')\">&nbsp</div>"
    end
    ret+"<div class='clear'></div>"
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/t_canvas_helper.rb
module TCanvasHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/twit_helper.rb
module TwitHelper
end

app/views/layouts/_footer.html.haml
#footer.container
  %p{:style =>"text-align:center;"}
    Jenua Boiko@
    #{DateTime.now.year}

app/views/layouts/_header.html.haml
#header.container
  %div.header_left
    =header_menu([['Parse', news_items_load_path], ['Parse last', news_items_load_last_path],
     ['Twits', twit_index_path], ['Canvas', t_canvas_index_path], ['Graphics and diagrams',
      t_canvas_build_path], ['Gallery', '#']])
    .clear

  %div.header_right
    %div.auth_div
      - unless user_signed_in?
        =link_to 'Registrate', new_user_registration_path
        or
        =link_to 'authorize', new_user_session_path
      - else
        %span Hello #{current_user.user_name}
        ||
        =link_to 'Exit', destroy_user_session_path, :method => "DELETE"

    %div.search_div
      = form_for :search, :url => request_search_index_path, :method => 'GET', :html => {:id => 'search_form'} do |f|
        = f.text_field 'search', :size => '20'
        = f.submit 'Search'
  .clear

app/views/layouts/_side_menu.html.haml
.side_menu.container
  %ol#side_menu.scrollable()
    -items.each do |item|
      - is_selected = selected_category != item.id.to_s
      %li.side_menu_item{:class => (!is_selected ? "selected_category" : "")}
        = link_to item.title, "#", :html => {:remote => true}, :onclick => "changeSelected($(this))"
        -#%ol.container{:id => "#{"cat"+item.id.to_s}",:class=>(is_selected ? "hidden_block" : "")}
        %ol.container{:id => "#{"cat"+item.id.to_s}", :class=>("hidden_block")}
          -item.topics.each do |topic|
            %li.side_menu_item{:class=>(selected_topic == topic.id.to_s ? "selected_topic" : "unselected_topic")}= link_to topic.title, news_category_topic_path(item,topic)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sphinx
    = stylesheet_link_tag 'web_app_theme'
    = javascript_include_tag :defaults, :cache => true
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} Sphinx
        #user-navigation
          %ul.wat-cf
            %li
              %a{:href => "#"}= t("web-app-theme.profile", :default => "Profile")
            %li
              %a{:href => "#"}= t("web-app-theme.settings", :default => "Settings")
            %li
              %a.logout{:href => "/logout"}= t("web-app-theme.logout", :default => "Logout")
        #main-navigation
          %ul.wat-cf
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
        #sidebar
          = yield :sidebar
        .clear
        #footer
          .block
            %p
              Copyright &copy; #{Time.now.year} Sphinx.

app/views/layouts/user_application.html.haml
!!!
%html{:dir => "ltr", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title Sphinx
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
    %meta{:content => "", :name => "keywords"}/
    %meta{:content => "", :name => "description"}/
    = javascript_include_tag :user_application
    = stylesheet_link_tag :user_application
    = csrf_meta_tag
  %body
    #body_content.container
      #content
        = render :partial => 'layouts/header'
        %table
          %tr
            %td.side_panel
              = render :partial => 'layouts/side_menu', :locals => {:items => @categories, :selected_category => @curr_category, :selected_topic => @curr_topic }
            %td.content.container
              = yield
      = render :partial => 'layouts/footer'